name: 🐛 Bug Report
description: Create a report to help us improve HonorBox
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of HonorBox is affected?
      options:
        - Frontend (React.js)
        - Backend (Node.js/Express.js)
        - Database (MongoDB)
        - Certificate Generation
        - Certificate Verification
        - Authentication
        - UI/UX
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear and concise description of what the bug is.
      placeholder: Describe what is happening...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser are you using?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 13.0, Ubuntu 22.04

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. Include screenshots if applicable.
      placeholder: Add any additional information, screenshots, or context...

  - type: checkboxes
    id: gssoc
    attributes:
      label: GSSoC Participation
      description: Are you participating in GirlScript Summer of Code?
      options:
      - label: I am participating in GSSoC 2025
        required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true